controller_node:
  ros__parameters:
    mass: 0.028
    gravity: 9.81

    dt: 0.001

    inertia_tensor: [21.09144e-6, 0.0,   0.0,
        0.0,   21.57533e-6, 0.0,
        0.0,   0.0,   35.86538e-5]

    Kp : [0.08, 0.0,   0.0,
        0.0,   0.08, 0.0,
        0.0,   0.0,  0.12]

    Kv : [0.1, 0.0,   0.0,
        0.0,   0.1, 0.0,
        0.0,   0.0,   0.13]

    KR : [1.5e-3, 0.0,   0.0,
        0.0,   1.5e-3, 0.0,
        0.0,   0.0,   5.0e-4]

    KOmega : [2.0e-4, 0.0,   0.0,
        0.0,   2.0e-4, 0.0,
        0.0,   0.0,   2.0e-4]